//! Deterministic `salicin.lock` generation for local path dependencies.

use std::fmt::Write as FmtWrite;
use std::fs::{self, OpenOptions};
use std::io::{self, Write as IoWrite};
use std::path::{Component, Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use semver::Version;

use crate::manifest::{DependencyGraph, Edition};

pub const LOCKFILE_NAME: &str = "salicin.lock";
pub const LOCKFILE_FORMAT_VERSION: u32 = 1;

/// Deterministic lock data derived from a complete dependency graph.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Lockfile {
    pub format: u32,
    pub packages: Vec<LockedPackage>,
}

impl Lockfile {
    /// Build sorted lock data. Package paths are relative to the root package
    /// whenever both paths share a filesystem root.
    pub fn from_graph(graph: &DependencyGraph) -> Self {
        let root = graph.root();
        let mut packages: Vec<LockedPackage> = graph
            .packages
            .iter()
            .map(|manifest| {
                let mut dependencies: Vec<LockedDependency> = manifest
                    .dependencies
                    .iter()
                    .map(|dependency| LockedDependency {
                        alias: dependency.alias.clone(),
                        name: dependency.package.name.clone(),
                        version: dependency.package.version.clone(),
                        path: lock_path(&root.package_root, &dependency.path),
                    })
                    .collect();
                dependencies.sort_by(|left, right| {
                    left.alias
                        .cmp(&right.alias)
                        .then_with(|| left.name.cmp(&right.name))
                        .then_with(|| left.version.cmp(&right.version))
                        .then_with(|| left.path.cmp(&right.path))
                });
                LockedPackage {
                    name: manifest.package.name.clone(),
                    version: manifest.package.version.clone(),
                    edition: manifest.package.edition,
                    path: lock_path(&root.package_root, &manifest.package_root),
                    dependencies,
                }
            })
            .collect();
        packages.sort_by(|left, right| {
            left.name
                .cmp(&right.name)
                .then_with(|| left.version.cmp(&right.version))
                .then_with(|| left.path.cmp(&right.path))
        });
        Self {
            format: LOCKFILE_FORMAT_VERSION,
            packages,
        }
    }

    /// Render canonical UTF-8 TOML with stable ordering and whitespace.
    pub fn to_text(&self) -> String {
        let mut output = String::from(
            "# This file is automatically generated by salic.\n\
             # Do not edit it by hand.\n",
        );
        writeln!(output, "format = {}", self.format).expect("writing to a string cannot fail");

        for package in &self.packages {
            output.push_str("\n[[package]]\n");
            write_toml_field(&mut output, "name", &package.name);
            write_toml_field(&mut output, "version", &package.version.to_string());
            write_toml_field(&mut output, "edition", package.edition.as_str());
            write_toml_field(&mut output, "path", &package.path);

            for dependency in &package.dependencies {
                output.push_str("\n[[package.dependencies]]\n");
                write_toml_field(&mut output, "alias", &dependency.alias);
                write_toml_field(&mut output, "name", &dependency.name);
                write_toml_field(&mut output, "version", &dependency.version.to_string());
                write_toml_field(&mut output, "path", &dependency.path);
            }
        }
        output
    }
}

/// One locked local package.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
    pub edition: Edition,
    pub path: String,
    pub dependencies: Vec<LockedDependency>,
}

/// One named dependency edge from a locked package.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LockedDependency {
    pub alias: String,
    pub name: String,
    pub version: Version,
    pub path: String,
}

/// Generate deterministic lock data from a previously validated graph.
pub fn generate_lockfile(graph: &DependencyGraph) -> Lockfile {
    Lockfile::from_graph(graph)
}

/// Generate canonical lockfile text from a previously validated graph.
pub fn render_lockfile(graph: &DependencyGraph) -> String {
    Lockfile::from_graph(graph).to_text()
}

/// Atomically replace a lockfile only when its bytes differ.
///
/// Returns `true` when the file changed and `false` when the existing content
/// was already current.
pub fn write_lockfile_if_changed(path: impl AsRef<Path>, lockfile: &Lockfile) -> io::Result<bool> {
    let path = path.as_ref();
    let contents = lockfile.to_text();
    match fs::read(path) {
        Ok(existing) if existing == contents.as_bytes() => return Ok(false),
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }

    atomic_write(path, contents.as_bytes())?;
    Ok(true)
}

/// Write `<root>/salicin.lock` only when the generated content changed.
pub fn write_package_lockfile(graph: &DependencyGraph) -> io::Result<bool> {
    let lockfile = Lockfile::from_graph(graph);
    write_lockfile_if_changed(graph.root().package_root.join(LOCKFILE_NAME), &lockfile)
}

fn write_toml_field(output: &mut String, name: &str, value: &str) {
    writeln!(output, "{name} = {}", toml_string(value)).expect("writing to a string cannot fail");
}

fn toml_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character if character.is_control() => {
                write!(escaped, "\\u{:04X}", character as u32)
                    .expect("writing to a string cannot fail");
            }
            character => escaped.push(character),
        }
    }
    escaped.push('"');
    escaped
}

fn lock_path(root: &Path, target: &Path) -> String {
    let path = relative_path(root, target).unwrap_or_else(|| target.to_path_buf());
    if path.as_os_str().is_empty() {
        return ".".to_owned();
    }
    path.to_string_lossy()
        .replace(std::path::MAIN_SEPARATOR, "/")
}

fn relative_path(from: &Path, to: &Path) -> Option<PathBuf> {
    let from_components: Vec<Component<'_>> = from.components().collect();
    let to_components: Vec<Component<'_>> = to.components().collect();
    let common = from_components
        .iter()
        .zip(&to_components)
        .take_while(|(left, right)| left == right)
        .count();

    if common == 0
        && (from.is_absolute()
            || to.is_absolute()
            || from_components.first() != to_components.first())
    {
        return None;
    }
    if from_components[common..]
        .iter()
        .any(|component| matches!(component, Component::Prefix(_) | Component::RootDir))
    {
        return None;
    }

    let mut relative = PathBuf::new();
    for component in &from_components[common..] {
        if !matches!(component, Component::CurDir) {
            relative.push("..");
        }
    }
    for component in &to_components[common..] {
        relative.push(component.as_os_str());
    }
    Some(relative)
}

static NEXT_TEMP_ID: AtomicU64 = AtomicU64::new(0);

fn atomic_write(path: &Path, contents: &[u8]) -> io::Result<()> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(LOCKFILE_NAME);
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();

    for _ in 0..100 {
        let id = NEXT_TEMP_ID.fetch_add(1, Ordering::Relaxed);
        let temporary = parent.join(format!(
            ".{file_name}.tmp-{}-{nonce}-{id}",
            std::process::id()
        ));
        let mut file = match OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temporary)
        {
            Ok(file) => file,
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error),
        };
        let result = (|| {
            file.write_all(contents)?;
            file.sync_all()?;
            drop(file);
            fs::rename(&temporary, path)
        })();
        if result.is_err() {
            let _ = fs::remove_file(&temporary);
        }
        return result;
    }

    Err(io::Error::new(
        io::ErrorKind::AlreadyExists,
        "could not allocate a temporary lockfile name",
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::load_dependency_graph;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT_TEST_ID: AtomicU64 = AtomicU64::new(0);

    struct TempDir(PathBuf);

    impl TempDir {
        fn new() -> Self {
            let id = NEXT_TEST_ID.fetch_add(1, Ordering::Relaxed);
            let path = std::env::temp_dir()
                .join(format!("salicin-lockfile-test-{}-{id}", std::process::id()));
            fs::create_dir_all(&path).unwrap();
            Self(path)
        }

        fn write(&self, relative: impl AsRef<Path>, contents: &str) {
            let path = self.0.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(path, contents).unwrap();
        }

        fn package(&self, directory: &str, name: &str, dependencies: &str) {
            self.write(format!("{directory}/src/lib.sc"), "let answer = 42\n");
            self.write(
                format!("{directory}/salicin.toml"),
                &format!(
                    "[package]\nname = \"{name}\"\nversion = \"1.0.0\"\nedition = \"2026\"\n{dependencies}"
                ),
            );
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn renders_sorted_stable_relative_lock_data() {
        let temp = TempDir::new();
        temp.package("shared", "shared", "");
        temp.package(
            "zeta",
            "zeta",
            "\n[dependencies]\nshared = { path = \"../shared\" }\n",
        );
        temp.package("alpha", "alpha", "");
        temp.package(
            "root",
            "root",
            "\n[dependencies]\nz = { path = \"../zeta\" }\na = { path = \"../alpha\" }\n",
        );
        let graph = load_dependency_graph(temp.0.join("root")).unwrap();

        let lockfile = Lockfile::from_graph(&graph);
        let first = lockfile.to_text();
        let second = Lockfile::from_graph(&graph).to_text();

        assert_eq!(first, second);
        assert_eq!(
            lockfile
                .packages
                .iter()
                .map(|package| package.name.as_str())
                .collect::<Vec<_>>(),
            ["alpha", "root", "shared", "zeta"]
        );
        assert!(first.contains("path = \".\""));
        assert!(first.contains("path = \"../shared\""));
        assert!(!first.contains(&temp.0.display().to_string()));
        let parsed: toml::Value = toml::from_str(&first).unwrap();
        assert_eq!(parsed["format"].as_integer(), Some(1));
    }

    #[test]
    fn writes_atomically_only_when_content_changes() {
        let temp = TempDir::new();
        temp.package("root", "root", "");
        let graph = load_dependency_graph(temp.0.join("root")).unwrap();
        let lockfile = generate_lockfile(&graph);
        let path = temp.0.join("root").join(LOCKFILE_NAME);

        assert!(write_lockfile_if_changed(&path, &lockfile).unwrap());
        assert_eq!(fs::read_to_string(&path).unwrap(), lockfile.to_text());
        assert!(!write_lockfile_if_changed(&path, &lockfile).unwrap());

        fs::write(&path, "stale\n").unwrap();
        assert!(write_package_lockfile(&graph).unwrap());
        assert_eq!(fs::read_to_string(path).unwrap(), lockfile.to_text());
    }

    #[test]
    fn escapes_toml_strings_and_relativizes_paths() {
        assert_eq!(toml_string("a\"b\\c\n"), "\"a\\\"b\\\\c\\n\"");
        assert_eq!(
            relative_path(Path::new("/a/root"), Path::new("/a/dep")),
            Some(PathBuf::from("../dep"))
        );
        assert_eq!(
            relative_path(Path::new("/a/root"), Path::new("/a/root")),
            Some(PathBuf::new())
        );
    }
}
